import React from 'react';
import { CheckCircle2, Circle, Clock, Lock, Map, Sparkles, TrendingUp, Upload, ArrowRight } from 'lucide-react';

const statusConfig = {
  done: { ring: 'border-success-300 bg-success-50', icon: CheckCircle2, iconColor: 'text-success-600', label: 'Completed', labelColor: 'bg-success-100 text-success-700' },
  active: { ring: 'border-primary-400 bg-primary-50', icon: Sparkles, iconColor: 'text-primary-600', label: 'In Progress', labelColor: 'bg-primary-100 text-primary-700' },
  locked: { ring: 'border-ink-200 bg-ink-50', icon: Lock, iconColor: 'text-ink-400', label: 'Locked', labelColor: 'bg-ink-100 text-ink-500' },
};

export function Roadmap({ resumeHistory, setViewMode }) {
  const latestResume = resumeHistory?.[0] || null;
  const rawRoadmap = latestResume?.roadmap || [];

  const handleUploadResumeClick = () => {
    const uploadInput = document.querySelector('input[type="file"]');
    if (uploadInput) {
      uploadInput.click();
    }
  };

  // Build dynamic phases from real backend data
  const phases = rawRoadmap.length > 0 ? rawRoadmap.map((stepText, idx) => {
    const progressVal = idx === 0 ? 100 : idx === 1 ? 65 : idx === 2 ? 20 : 0;
    const statusVal = idx === 0 ? 'done' : idx === 1 ? 'active' : 'locked';
    const durationVal = idx === 0 ? '4 weeks' : idx === 1 ? '6 weeks' : idx === 2 ? '5 weeks' : '3 weeks';
    
    // Distribute skills across phases dynamically
    const skills = latestResume.technical_skills?.slice(idx * 2, (idx + 1) * 2) || [];
    
    // Split key labels
    const parts = stepText.split(':');
    const title = parts[0]?.trim() || `Phase ${idx + 1}`;
    const subtitle = parts.slice(1).join(':')?.trim() || stepText;

    return {
      id: idx + 1,
      title: title,
      subtitle: subtitle,
      progress: progressVal,
      status: statusVal,
      duration: durationVal,
      skills: skills,
      modules: [
        { name: 'Core concepts review', done: idx === 0 },
        { name: 'Practical implementation project', done: false }
      ]
    };
  }) : [];

  const overallProgress = phases.length > 0 ? Math.round(phases.reduce((acc, p) => acc + p.progress, 0) / phases.length) : 0;

  if (phases.length === 0) {
    return (
      <div className="px-4 sm:px-6 py-6 max-w-4xl mx-auto text-center animate-fade-in">
        <div className="card p-10 sm:p-16">
          <div className="flex items-center justify-center w-16 h-16 rounded-2xl bg-primary-50 mx-auto">
            <Map className="w-8 h-8 text-primary-600" />
          </div>
          <h3 className="font-display font-semibold text-ink-900 text-lg mt-6">
            No Roadmap Generated Yet
          </h3>
          <p className="text-sm text-ink-500 mt-2 max-w-sm mx-auto">
            Please upload a resume first. Our AI agents will analyze your profile and construct a personalized 4-phase learning roadmap.
          </p>
          <button 
            onClick={handleUploadResumeClick}
            className="btn-primary mt-6 mx-auto font-medium"
          >
            <Upload className="w-4 h-4" />
            Upload Resume
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="px-4 sm:px-6 py-6 max-w-4xl mx-auto space-y-6">
      {/* Header Info Panel */}
      <div className="card p-6 animate-fade-in">
        <div className="flex flex-col sm:flex-row items-start gap-4">
          <div className="flex items-center justify-center w-12 h-12 rounded-2xl bg-gradient-to-br from-primary-500 to-primary-700 shrink-0 text-white">
            <Map className="w-6 h-6" />
          </div>
          <div className="flex-1">
            <h2 className="font-display font-bold text-ink-900 text-xl">Your Career Roadmap</h2>
            <p className="text-sm text-ink-500 mt-1">
              A personalized path generated by CareerPilot AI. Complete phases sequentially to build technical mastery.
            </p>
            <div className="flex flex-wrap gap-6 mt-4 pt-4 border-t border-ink-100">
              <div className="flex items-center gap-2">
                <span className="text-2xl font-display font-bold text-ink-900">{overallProgress}%</span>
                <span className="text-xs text-ink-500">Overall progress</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-2xl font-display font-bold text-ink-900">{phases.filter(p => p.status === 'done').length}</span>
                <span className="text-xs text-ink-500">Phases completed</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Roadmap phases grid list */}
      <div className="space-y-6">
        {phases.map((phase, i) => {
          const cfg = statusConfig[phase.status] || statusConfig.locked;
          const StatusIcon = cfg.icon;
          return (
            <div
              key={phase.id}
              className="card p-5 sm:p-6 animate-fade-in hover:border-primary-200 transition-all duration-300"
              style={{ animationDelay: `${i * 100}ms` }}
            >
              <div className="flex flex-col md:flex-row gap-5">
                {/* Visual status indicators */}
                <div className="flex items-start gap-4 flex-1">
                  <div className={`flex items-center justify-center w-12 h-12 rounded-2xl border-2 border-dashed shrink-0 ${cfg.ring}`}>
                    <StatusIcon className={`w-5 h-5 ${cfg.iconColor}`} />
                  </div>
                  <div className="min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="text-xs font-bold text-primary-600 tracking-wide uppercase">Phase {phase.id}</span>
                      <span className={`badge text-[10px] font-semibold ${cfg.labelColor}`}>
                        {cfg.label}
                      </span>
                    </div>
                    <h3 className="font-display font-semibold text-ink-900 text-[16px] mt-1">
                      {phase.title}
                    </h3>
                    <p className="text-sm text-ink-500 mt-1">
                      {phase.subtitle}
                    </p>
                    
                    {/* Skills tag group */}
                    {phase.skills.length > 0 && (
                      <div className="flex flex-wrap gap-1.5 mt-3">
                        {phase.skills.map(sk => (
                          <span key={sk} className="badge bg-ink-100 text-ink-600 text-[11px] font-medium">{sk}</span>
                        ))}
                      </div>
                    )}
                  </div>
                </div>

                {/* Progress bar info */}
                <div className="w-full md:w-56 shrink-0 pt-2 border-t md:border-t-0 md:pt-0 border-ink-100 flex flex-col justify-between">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs text-ink-500 font-medium flex items-center gap-1">
                      <Clock className="w-3.5 h-3.5" />
                      {phase.duration}
                    </span>
                    <span className="text-sm font-semibold text-ink-800">{phase.progress}%</span>
                  </div>
                  <div className="h-2 rounded-full bg-ink-100 overflow-hidden mb-4">
                    <div
                      className="h-full rounded-full bg-primary-500 transition-all duration-700"
                      style={{ width: `${phase.progress}%` }}
                    />
                  </div>
                  
                  {/* Phase Module Task list */}
                  <div className="space-y-1.5">
                    {phase.modules.map((m, mIdx) => (
                      <div key={mIdx} className="flex items-center gap-2">
                        {m.done ? (
                          <CheckCircle2 className="w-3.5 h-3.5 text-success-500 shrink-0" />
                        ) : (
                          <Circle className="w-3.5 h-3.5 text-ink-300 shrink-0" />
                        )}
                        <span className="text-xs text-ink-600 truncate">{m.name}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

export default Roadmap;
